### ISSUE TITLE
First task accomplished, with several notes

### ISSUE THREAD

**Issue by wisnuops** [squest/data-science#13]
I have created the statistics functions here:

https://github.com/wisnuops/data-science/blob/master/training/wisnuops/src/wisnuops/core.clj

and the testing functions here:

https://github.com/wisnuops/data-science/blob/master/training/wisnuops/src/wisnuops/core.clj

Several notes:
- **means** only work for non nil input. And the input should be numbers. I guess this is acceptable, or isn't it?
- Most of the functions return :key-not-exist if the key doesn't exist in the themap.
- **(freq [key themap])** returns {:key-not-exist n} if the key doesn't exist. Probably need to be fixed.
- **(modes [key themap])** returns [:key-not-exist] if the key doesn't exist. Probably need to be fixed.
- **(freq-by [key themap])** would return {:key-not-exist n} if the key doesn't exist. Probably need to be fixed.
- According to Wikipedia, there are 3 methods of calculating **quartile**. Every method have different results if the dataset have odd number of data. I use the Method No. 1 in Wikipedia, the same method that we use when teaching to high school students. It is different from what is used in Microsoft Excel. So I cannot use Microsoft Excel to run the testing.
- The **quartile** function only work if the data set have more than 2 elements.
- The formula that we use to calculate **decile** is the same formula that we use in https://www.zenius.net/c/1374/data-tunggal-teori ("desil" video). It will return :coll-less-than-10 if the collection is less than ten.
- I haven't used [standard clojure style guide](https://github.com/bbatsov/clojure-style-guide), but hopefully it is not too hard to understand. Will fix it soon. :)

OK then. So, what's next?

I want to create a pull request to https://github.com/squest/data-science
but I am not sure whether it could possibly create a conflict.

**Comment by squest** [comment]
By routinely sync and update from master, it should not cause any conflict. Try sync it and update it, and then make a pull request.

**Comment by wisnuops** [comment]
Yesterday I tried to update and sync but Donna's and Davin's folder didn't
get copied to my repository. I should get the copy first before making a
pull request, right?

**Comment by squest** [comment]
Yes, and the order of operations matter. Sync first, then update from master, and lastly pull request.
